name: C Compilation

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2



    - name: Compile C code
      run: |
        sudo apt install -y git wget pkg-config autoconf gcc make libusb-1.0-0-dev librtlsdr-dev librtlsdr0 libncurses-dev zlib1g-dev zlib1g libzstd-dev libzstd1

    - name: Compile jemalloc
      run: |
        JEMALLOC_BDIR=$(mktemp -d) && \
        git clone --depth 1 https://github.com/jemalloc/jemalloc $JEMALLOC_BDIR && \
        cd $JEMALLOC_BDIR && \
        ./autogen.sh && \
        ./configure --with-lg-page=14 && \
        make -j$(nproc) 
        # make install && \
        # rm -rf $JEMALLOC_BDIR
        echo $PWD
        cd /home/runner/work/readsb/readsb
        echo $PWD
        # cd /${{ env.WORKING_DIRECTORY }}
        make AIRCRAFT_HASH_BITS=11 RTLSDR=yes OPTIMIZE="-O3 -march=native"
        ./readsb --help

    - name: Archive ubuntu build
      uses: actions/upload-artifact@v2
      with:
          name: readsb-ubuntu.zip
          path: /home/runner/work/readsb/readsb/readsb
